name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "owner ${{ github.event.repository.owner.login }}!"
          echo "repo ${{ github.event.repository.name }}!"