name: Manually triggered workflow
on:
  workflow_dispatch:
    inputs:
      number:
        description: 'Pull Request Number'
        required: true
jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.number }}!"
  chromatic:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'refs/pull/${{ github.event.inputs.number }}/head'
        fetch-depth: 0
    - uses: octokit/request-action@v2.x
      id: get_branch_name
      with:
        route: GET /repos/{owner}/{repo}/pulls/{pull_number}
        owner: rkcevscfou
        repo: github-actions-private
        pull_number: ${{ github.event.inputs.number }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: echo "Data ${{ fromJson(steps.get_branch_name.outputs.data) }}"
    # - uses: actions/setup-node@v1
    #   with:
    #     node-version: '>=14.16.0 14'
    # - run: npm ci
    # - run: npx chromatic --project-token ${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded